### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cuge1995** [xiaogangw-zz/cascaded-point-completion#3]
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import tf_util
  File "./utils/tf_util.py", line 7, in <module>
    from tf_sampling import farthest_point_sample, gather_point
  File "/home/cuge/Documents/point/cascaded-point-completion/tf_ops/sampling/tf_sampling.py", line 12, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/cuge/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/cuge/Documents/point/cascaded-point-completion/tf_ops/sampling/tf_sampling_so.so: cannot open shared object file: No such file or directory

**Comment by xiaogangw-zz** [comment]
Hi, @cuge1995, thanks for your interest on our work. Please follow [PointNet++](https://github.com/charlesq34/pointnet2) to compile customized TF operators. You may need to change the related library paths if necessary.

**Comment by cuge1995** [comment]
thanks

**Comment by ZiqinZhou66** [comment]
After I run tf_sampling_compile.sh and tf_grouping_compile.sh to generate XXX_so.so files with changing PATH, then I try to run train.py. However I get the following error:
tensorflow.python.framework.erros_impl.NotFoundError: /home/XXX/tf_sampling_so.so: undefined symbol: _ZTIN10tensorflow120XXXX
I figure out it happened because my version of gcc is higher than 4 (I use 7.5.0), so I delete the parameter setting "-D_GLIBCXX_USE_CXX11_ABI=0" in the original tf_XXX_compile.sh and run them again. It seems to work. There is no error that comes from tf_XXX_so.so.
However, the same error raised from tf_nndistance_so.so which is not compiled from XXX.sh file. Even I delete the same paramters setting in /pc_distance/makefile it does not work. I wonder what is your gcc version? How to solve the bug I'm facing now? Do I need to generate tf_nndistance_so.so with my own configuration?
Looking forward to your reply.

**Comment by ZiqinZhou66** [comment]
However~
After I run tf_sampling_compile.sh and tf_grouping_compile.sh to generate XXX_so.so files with changing PATH, then I try to run train.py. However, I get the following error:
tensorflow.python.framework.erros_impl.NotFoundError: /home/XXX/tf_sampling_so.so: undefined symbol: _ZTIN10tensorflow120XXXX
I figure out it happened because my version of gcc is higher than 4 (I use 7.5.0), so I delete the parameter setting "-D_GLIBCXX_USE_CXX11_ABI=0" in the original tf_XXX_compile.sh and run them again. It seems to work. There is no error that comes from tf_sampling_so.so and tf_grouping_so.so.
However, the same error raised from tf_nndistance_so.so which is not compiled from XXX.sh file. Even I delete the same parameters setting in /pc_distance/makefile it does not work. I wonder what is your gcc version? How to solve the bug I'm facing now? Do I need to generate tf_nndistance_so.so with my own configuration?
Looking forward to your reply.

**Comment by ZiqinZhou66** [comment]
Hello~
After I run tf_sampling_compile.sh and tf_grouping_compile.sh to generate XXX_so.so files with changing PATH, then I try to run train.py. However, I get the following error:
tensorflow.python.framework.erros_impl.NotFoundError: /home/XXX/tf_sampling_so.so: undefined symbol: _ZTIN10tensorflow120XXXX
I figure out it happened because my version of gcc is higher than 4 (I use 7.5.0), so I delete the parameter setting "-D_GLIBCXX_USE_CXX11_ABI=0" in the original tf_XXX_compile.sh and run them again. It seems to work. There is no error that comes from tf_sampling_so.so and tf_grouping_so.so.
However, the same error raised from tf_nndistance_so.so which is not compiled from XXX.sh file. Even I delete the same parameters setting in /pc_distance/makefile it does not work. I wonder what is your gcc version? How to solve the bug I'm facing now? Do I need to generate tf_nndistance_so.so with my own configuration?
Looking forward to your reply.
